<?php

use App\Models\UserStatus;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddPacketSeeder extends Seeder
{
    public function run()
    {
        DB::table('packets')
            ->insert([
                [
                    'id' => 1,
                    'name' => 'Classic',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 60,
                    'css_color' => '#9f85a2',
                    'available_level' => '4',
                    'user_status_id' => UserStatus::CONSULTANT,
                    'is_active' => true,
                    'sort_num' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 2,
                    'name' => 'Premium',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 120,
                    'css_color' => '00758a',
                    'available_level' => '6',
                    'user_status_id' => UserStatus::PREMIUM_MANGER,
                    'is_active' => true,
                    'sort_num' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 3,
                    'name' => 'VIP',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 180,
                    'css_color' => 'FE408A',
                    'available_level' => '8',
                    'user_status_id' => UserStatus::VIP_MANAGER,
                    'is_active' => true,
                    'sort_num' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 4,
                    'name' => 'GAP',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 300,
                    'css_color' => 'a83255',
                    'available_level' => '8',
                    'user_status_id' => UserStatus::PASSIV,
                    'is_active' => true,
                    'sort_num' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 5,
                    'name' => 'GAPTechno',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 60,
                    'css_color' => '#cba943',
                    'available_level' => '4',
                    'user_status_id' => UserStatus::ACTIV1,
                    'is_active' => true,
                    'sort_num' => 5,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 6,
                    'name' => 'GAPAuto',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 120,
                    'css_color' => '2285E3',
                    'available_level' => '6',
                    'user_status_id' => UserStatus::ACTIV2,
                    'is_active' => true,
                    'sort_num' => 6,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => 7,
                    'name' => 'GAPHome',
                    'description_kz' => '',
                    'description_ru' => '',
                    'image' => '',
                    'price' => 300,
                    'css_color' => '#5d5f98',
                    'available_level' => '8',
                    'user_status_id' => UserStatus::ACTIV3,
                    'is_active' => true,
                    'sort_num' => 7,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]);
    }
}
